### ISSUE TITLE
Game wont save

### ISSUE THREAD

**Issue by Yalvor** [virtual-programming/overlord2-linux#10]
![20161008050230_1](https://cloud.githubusercontent.com/assets/22283677/19209543/7572d168-8d1d-11e6-96c4-2f3bd9a8b98b.jpg)
![20161008050612_1](https://cloud.githubusercontent.com/assets/22283677/19209544/7674055a-8d1d-11e6-9249-0da698a78a90.jpg)

**Comment by vpltd-kgalaj** [comment]
First thing I can think of is file/directory access permissions, ie. if the game doesn't have access permissions to a saved game file it tries to update, or the directory the files is in. Normally the game would create these files by itself, so it would have access rights, but if the files were copied over from some other account, than their owner could be different than the user from whose account the game is launched.

**Comment by Yalvor** [comment]
The problem was in the profile name - somehow the game added a symbol that looked like a "D" with a minus - "Save - DProfileName". Fixed by remaking/renaming the profile. Probably have to do something with issue #6
