### ISSUE TITLE
glitch after a while on Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by Dea1993** [virtual-programming/overlord2-linux#5]
I'm playing the game on this system:
OS: Ubuntu 16.04 64bit
CPU: A10 8700p (carrizo)
GPU: radeon r6
Driver: opensource AMDGPU kernel driver Mesa 11.2
Kernel: 4.7

but i've a very critical issue.
after a while that i play, the screen became all buggy/glitched, and is impossible to play.

as you can see in this screenshot i can't se anything

![20160728193222_1](https://cloud.githubusercontent.com/assets/5217483/17223460/f150629a-54fc-11e6-93bd-e7a6d5c80404.jpg)

when i kill the game (with alt+f4 or clicking on X button) the problem persist (as you can see in this screenshot)

![schermata del 2016-07-28 19-34-08](https://cloud.githubusercontent.com/assets/5217483/17223496/1a4ba344-54fd-11e6-8590-76870d1a29ef.png)

please solve the issue, thanks

**Comment by vpltd-peterm** [comment]
This is a bug in Mesa itself, and my own system is affected. If you check your kernel logs you will probably see GPU errors in there.

I've already filed a bug against Mesa for this.

**Comment by vpltd-peterm** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=97022

**Comment by Dea1993** [comment]
thanks for the answer.
so we must hope that mesa developers will fix soon

**Comment by vpltd-peterm** [comment]
Ubuntu Xenial is only shipping the 11.2.0 version of Mesa, not the latest 12.1.0 series. It looks as if Ubuntu Yakkety will be shipping 12.0.1. You can see info for the packages here:

https://launchpad.net/ubuntu/+source/mesa

So for the time being, you will need to use a PPA like Oibaf in order to get the latest Mesa driver.

**Comment by vpltd-peterm** [comment]
With the latest build of Mesa 12.1.0, available in Oibaf today, the display corruption/system lockup problems should be solved. Please try it :)

**Comment by vpltd-peterm** [comment]
Issue is fixed using Mesa 12.1.0, as of commit bc5df3b321c5393b2f10115cfa5acc8f11bd7146
